### ISSUE TITLE
Need to scroll variables list up to get to the "Close" button

### ISSUE THREAD

**Issue by DmitryKonev** [mikeplavsky/Fitnesse-Variables#2]
If "Close" button will be fastened in the right-top corner, it could be more convenient.
Auto-exit on click outside of variables list also could be fine.

Thank you & BR,
Dmitry.

**Comment by mikeplavsky** [comment]
Yep! Pull request are welcome! :)

**Comment by mikeplavsky** [comment]
@DmitryKonev Hey, Dmitry, I've made this "Auto-exit on click outside of variables list also could be fine." Could you please check and see if it works for you? Just upgrade to the latest version - 0.1.3.2

**Comment by dkonev-quest** [comment]
It works good! Thank you, Mike!
